# Generated by Django 6.0.3 on 2026-08-27 15:08

import django.db.models.deletion
from django.db import migrations, models


def backfill_settlement_batches(apps, schema_editor):
    """Wrap each session's existing (pre-history) settlement rows in one batch.

    Old code always deleted+recreated settlements on every recompute, so every
    session has at most one implicit "current" batch worth of rows here.
    """
    Session = apps.get_model("ledger", "Session")
    SettlementBatch = apps.get_model("ledger", "SettlementBatch")

    session_ids = (
        Session.objects.filter(settlements__isnull=False).values_list("id", flat=True).distinct()
    )
    for session_id in session_ids:
        batch = SettlementBatch.objects.create(session_id=session_id, reason="migrated")
        Session.objects.get(id=session_id).settlements.update(batch=batch, is_current=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0018_ledgeruser_supabase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionsettlement',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='SettlementBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=32)),
                ('discrepancy', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_batches', to='ledger.session')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='sessionsettlement',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ledger.settlementbatch'),
        ),
        migrations.RunPython(backfill_settlement_batches, noop_reverse),
        migrations.AlterField(
            model_name='sessionsettlement',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ledger.settlementbatch'),
        ),
    ]
